import {Karla} from 'next/font/google';
import './globals.css';
// import BackgroundSVG from './components/BackgroundSVG';

// eslint-disable-next-line new-cap
const karla = Karla({subsets: ['latin']});

export const metadata = {
  title: 'Quizzical',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      {/* <BackgroundSVG /> */}
      <body className={karla.className}>{children}</body>
    </html>
  );
}
